general {
    # Optional: A subtle Everforest grey border looks much cleaner in light mode than 0 borders
    border_size = 1
#    col.active_border = rgba(5c6a7266)
#    col.inactive_border = rgba(00000000)
    col.active_border = rgba(00000000)
    col.inactive_border = rgba(00000000)

}

decoration {
    rounding = 10 # Slightly rounder for the macOS look
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = true
    }
}

# Force ALL windows to be completely solid (kills the glass effect everywhere)
# windowrule = opacity 1.0 override 1.0 override, match:class .*
