general {
    col.active_border = rgba(00000000)
    col.inactive_border = rgba(00000000)
}

decoration {
    rounding = 5
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = true
    }
}
